rvm:
  - 2.2.3
env:
  - RAILS_ENV=test
script:
  - bundle exec rake db:schema:load
  - bundle exec rake spec
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database workshops_test;' -U postgres
  - psql -c 'create user workshops;' -U postgres
addons:
  postgresql: '9.3'
