connection: &connection
  adapter: postgresql
  encoding: unicode
  host:     localhost
  pool: 5

development:
  <<: *connection
  username: workshops
  password:
  database: workshops_development

test: &test
  <<: *connection
  database: workshops_test
